### ISSUE TITLE
need proper error messages when pssm does not match pdb

### ISSUE THREAD

**Issue by LilySnow** [DeepRank/iScore#14]
When pssm file does not match the pdb file, K matrix is empty.  Can we give a proper error messages when pssm does not match pdb? Can we also give proper error messages when K matrix is empty?

**Comment by CunliangGeng** [comment]
The reason we provide the `map_pssm2pdb` is to avoid this problem. By default, the package use the mapped pdb and pssm. Considering the complex and messy data in CAPRI, we should always generate the mapped pdb and pssm in the first step.

**Comment by CunliangGeng** [comment]
Will update doc to make users aware of the importance of pssm2pdb mapping.
