### ISSUE TITLE
need the PSSM class to allow input sequence

### ISSUE THREAD

**Issue by LilySnow** [DeepRank/iScore#15]
The current PSSM class takes a pdb file as input and extracts sequences from the pdb file. However, many pdb files do not have a complete sequence (missing segments) and this will affect the quality of pssm. 

Can we make the pssm class to allow the user input sequences?

**Comment by CunliangGeng** [comment]
iScore has such function `iScore/iScore/pssm/pssm.py`. 
What you mean, I guess, is this file  `iScore/iScore/pssm/map_pssm2pdb.py`, which is used by the `pssm.py`.

**Comment by CunliangGeng** [comment]
check #18.
