### ISSUE TITLE
need pssm mapping code to be more flexible

### ISSUE THREAD

**Issue by LilySnow** [DeepRank/iScore#18]
Many times, we just need to calculate pssm once (time-consuming) and map it to all the pdb files (fast). The current code does not seem to allow it.

**Comment by CunliangGeng** [comment]
Really? The PSSM class has `map_pssm` function.

**Comment by NicoRenaud** [comment]
I thought it was the case as well. It's maybe that we need better documentation :)

**Comment by LilySnow** [comment]
Yes, that function is there. But it is built in the class and that class requires a pdb file as input. See issue #15.

**Comment by CunliangGeng** [comment]
The function can actually do that by ignoring the `PSSM.get_fasta()` step, instead you create a `./fasta` folder and put the customed fasta file to this folder, other steps are same as previous (https://iscoredoc.readthedocs.io/en/latest/pssm.html). 

I will close this issue and update the doc then.

**Comment by LilySnow** [comment]
Thanks. One example in the doc should be enough.

**Comment by CunliangGeng** [comment]
Independent PSSMGen will be used (https://github.com/DeepRank/PSSMGen), clear examples are shown in README.
