### ISSUE TITLE
a bug with "mpiexec -n ${NPROC} iScore.predict"

### ISSUE THREAD

**Issue by LilySnow** [DeepRank/iScore#21]
When I run "mpiexec -n ${NPROC} iScore.predict" on capri target 161, I ran into a bug.

1. I run this command for the first time, I will get the following error message: 

> Reusing kernels in ./kernel/
> Traceback (most recent call last):
>   File "/home/lixue/tools/iScore/bin/iScore.predict", line 57, in <module>
>     iscore_svm(load_model=None,package_name=args.archive,testID=args.ground_truth)
>   File "/home/lixue/tools/iScore/iScore/graphrank/rank.py", line 402, in iscore_svm
>     testdata = DataSet(trainID,Kfile,maxlen,testID=testID)
>   File "/home/lixue/tools/iScore/iScore/graphrank/rank.py", line 29, in __init__
>     self.test_name, self.test_class = self._get_ids(testID)
>   File "/home/lixue/tools/iScore/iScore/graphrank/rank.py", line 80, in _get_ids
>     nc = len(idlist[0])
> IndexError: list index out of range

The folder of 'graph' will be calculated successfully but 'kernel' folder will not.

2. I then deleted the folder of 'kernel', and rerun the same command. This time the kernel folder is calculated correctly. But I got the following error message:

> Traceback (most recent call last):
>   File "/home/lixue/tools/iScore/bin/iScore.predict", line 63, in <module>
>     iscore()
>   File "/home/lixue/tools/iScore/iScore/function/score.py", line 17, in __init__
>     self.read_graphrank()
>   File "/home/lixue/tools/iScore/iScore/function/score.py", line 56, in read_graphran
>     data.append(self.features[m]['grank'])
> KeyError: 'grank'

3. Then I ran the same command the 3rd time, `iScorePredict.dat` is finally generated. 

The data is on alcazar: `/home/lixue/CAPRI/Capri48/t161/iscore/before_cleaning/results_li`

**Comment by CunliangGeng** [comment]
# Without MPI
iScore.predict --archive ../train/training_set.tar.gz

# With MPI
mpiexec -n ${NPROC} iScore.predict**.mpi** --archive ../train/training_set.tar.gz

**Comment by NicoRenaud** [comment]
To avoid this confusion it might be a good idea to keep only the MPI execs.

**Comment by CunliangGeng** [comment]
I have updated the README to clearly show how to use them.
