### ISSUE TITLE
fail to repeat 684 dataset result

### ISSUE THREAD

**Issue by jiyanbio** [DeepRank/iScore#29]
**Describe the bug**
when I run iScore.predict on one of data sets, such as 1ACB, different iScores were given.  In 684, the file refers to 1ACB.iScore. In the result of iScore.predict, the file refers to iScorePredict.dat 

**Environment:**
- OS system: Linux VM-88-194-centos 3.10.107-1-tlinux2_kvm_guest-0049
- Version: 
- Branch commit ID: lastest
- Inputs: the same pdb and pssm in 684

**To Reproduce**
Steps/commands to reproduce the behaviour:
 1.   iScore.predict 

**Expected Results**
Ideally, I want to get the same result files which were provided in 684 datasets including haddock energy scores.

**Comment by NicoRenaud** [comment]
Thanks for reporting the issue. We will look into it asap but due to the Covid crisis we are a bit slower than usual.

**Comment by CunliangGeng** [comment]
Hi @jiyanbio , thanks for reporting this issue. 

If I understand your question correctly, you want to get Haddock score using this package. Unfortunately, the iScore package cannot directly provide you Haddock score. The Haddock scores in dataset 684 were not generated by this package but by Haddock software itself. 

However, if you have Haddock models (Haddock pdb files), it's possible to calculate the Haddock score with iScore package. Let's take the `1ACB_1w.pdb` file from dataset 684 as an example. Before reading the following example, it's better to have a look at what Haddock score is: https://www.bonvinlab.org/software/haddock2.2/scoring/.

Example: using iScore package to extract Haddock energies
```python
>>> from iScore.energetic.haddock_energy import HaddockEnergy
>>> he = HaddockEnergy('1ACB_1w.pdb')
>>> he.read_energies()
# Eelec: electrostatic intermolecular energy
>>> he.ec
-256.513
# Evdw: van der Waals intermolecular energy
>>> he.evdw
-26.9989
Edesol: desolvation energy
>>> he.edesolv
16.2592
```
What the code above does is actually to extract the energy values from `1ACB_1w.pdb` file. You could open the `1ACB_1w.pdb` file and should find those values in the header. 

After extracting the Haddock energies, then you can calculate the Haddock score with the equation given in the page https://www.bonvinlab.org/software/haddock2.2/scoring/. The Haddock models in dataset 684 are from Haddock `water` stage, so you need to use this euqation: `HADDOCKscore-water =  1.0 Evdw + 0.2 Eelec + 1.0 Edesol +  0.1 Eair`.  The `Eair` is 0, so it can be ignored.

Free to contact me if you have further questions.
